package main

import (
	"fmt"
	"net/url"
	"os"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/theCompanyDream/user-angular/apps/backend/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/theCompanyDream/user-angular/apps/backend/controller"
	"github.com/theCompanyDream/user-angular/apps/backend/repository"
)

func main() {
	repository.InitDB()
	server := echo.New()

	server.HTTPErrorHandler = controller.HttpErrorHandler

	// Middleware
	server.Use(middleware.Recover())
	server.Use(middleware.Logger())

	// Define main routes
	server.GET("/swagger/*", echoSwagger.WrapHandler)
	server.GET("/", controller.Home)
	server.GET("/users", controller.GetUsers)
	server.GET("/user/:id", controller.GetUser)
	server.POST("/user", controller.CreateUser)
	server.PUT("/user/:id", controller.UpdateUser)
	server.DELETE("/user/:id", controller.DeleteUser)

	// Set up reverse proxy configuration
	mainDomain := os.Getenv("MAIN_DOMAIN")
	httpPort := os.Getenv("HTTP_PORT")

	if mainDomain != "" && httpPort != "" {
		proxyURL := fmt.Sprintf("http://%s:%s", mainDomain, httpPort)
		proxyTarget, err := url.Parse(proxyURL)
		if err != nil {
			server.Logger.Fatalf("Failed to parse proxy URL: %v", err)
		}

		// Set up proxy middleware for the API group
		targets := []*middleware.ProxyTarget{
			{
				URL: proxyTarget,
			},
		}

		// Apply the proxy middleware only to specific paths that should be proxied
		// You might need to adjust this based on your specific requirements
		proxyGroup := server.Group("/proxy")
		proxyGroup.Use(middleware.ProxyWithConfig(middleware.ProxyConfig{
			Balancer: middleware.NewRoundRobinBalancer(targets),
		}))
	} else {
		server.Logger.Warn("Proxy configuration not set: MAIN_DOMAIN or HTTP_PORT environment variables missing")
	}

	// Start the server
	server.Logger.Info("Server is running...")
	port := os.Getenv("BACKEND_PORT")
	if port != "" {
		serverStartCode := fmt.Sprintf(":%s", port)
		server.Logger.Fatal(server.Start(serverStartCode))
	} else {
		server.Logger.Fatal(server.Start(":3000"))
	}
}